version: "3.7"

services:
  aurelia-ej-2-bridge-demo:
    image: aurelia-ej-2-bridge-demo:0.1.0
    build:
      context: . # relative to docker-compose.yml
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    restart: unless-stopped
